import type { Metadata } from "next";
import "./globals.css";
import LayoutComponent from "./LayoutComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <LayoutComponent>
        <body className="">{children}</body>
      </LayoutComponent>
    </html>
  );
}
